AspNetMVC/Models/Aluno.cs
namespace AspNetMVC.Models
{
    public class Aluno
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Situacao { get; set; }
        public int Matricula { get; set; }

        public bool Verificacao = false;
    }
}

AspNetMVC/Models/ErrorViewModel.cs
namespace AspNetMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AspNetMVC/Controllers/AlunoController.cs
using AspNetMVC.Models;
using AspNetMVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMVC.Controllers
{
    public class AlunoController : Controller
    {
        public async Task<IActionResult> Index(int id)
        {
            //Aluno a1 = new Aluno();
            //a1.Id = 1;
            //a1.Nome = "Camilo";

            //Aluno a2 = new Aluno();
            //a2.Id = 2;
            //a2.Nome = "Rafael";

            //List<Aluno> alunos = new List<Aluno>();
            //alunos.Add(a1);
            //alunos.Add(a2);

            //ViewBag.ListaAlunos = alunos;
            //ViewBag.ID = id;

            AlunoServices alunoServices = new AlunoServices();
            Aluno aluno = await alunoServices.Integracao(id);
            
            if(aluno.Id == 0)
            {
                return View("NotFound");
            }

            ViewBag.aluno = aluno;

            


            return View();
        }

        public async Task<IActionResult> Lista()
        {

            AlunoServices alunoServices = new AlunoServices();
            var alunos = await alunoServices.GetAlunos();

            if (alunos.Count == 0)
            {
                return View("NotFound");
            }

            ViewBag.ListaAlunos = alunos;




            return View();
        }
    }
}

AspNetMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspNetMVC.Models;

namespace AspNetMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        ViewBag.Hello = "Hello World";
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AspNetMVC/Views/Aluno/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    Aluno aluno = ViewBag.aluno;
    

}

<h1>Pagina De Aluno</h1>
<p>ID: @aluno.Id </p>
<p>Nome: @aluno.Nome </p>
<p>Matricula: @aluno.Matricula</p>
<p>Situação: @aluno.Situacao</p>

@*@foreach (Aluno item in ViewBag.ListaAlunos)
{
    <p>@item.Nome</p>
}*@

AspNetMVC/Views/Aluno/Lista.cshtml
@{
    ViewData["Title"] = "Lista De Alunos";
    Layout = "~/Views/Shared/_Layout.cshtml";

   

}

    <h1>Pagina De Aluno</h1>

@foreach (Aluno aluno in ViewBag.ListaAlunos)
{
    <p><a href="/Aluno/Index/@aluno.Id">ID: @aluno.Id</a></p>
    <p>Nome: @aluno.Nome </p>
    <p>Matricula: @aluno.Matricula</p>
    <p>Situação: @aluno.Situacao</p>
}

AspNetMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2>@ViewBag.Hello</h2>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspNetMVC/Views/Shared/NotFound.cshtml
<h1>404 Not Found!</h1>

AspNetMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Lista">Alunos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AspNetMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>